MODEL:
  TYPE: glam_swin
  NAME: glam_swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  GLAMSWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
    GT_NUM: 10


# 10gt : 15min par epoch