MODEL:
  TYPE: glam_swin
  NAME: glam_swin_base_patch4_window7_224
  DROP_PATH_RATE: 0.5
  GLAMSWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
    GT_NUM: 10

# 10gt : 30min par epoch